version: '0.2'
env:
  variables:
    AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
    AWS_REGION: $AWS_REGION
phases:
  install:
    runtime-versions:
      nodejs: 14.21.3
    commands:
      - echo Installing dependencies...
      - npm install --force
  pre_build:
    commands:
      - echo Building project...
      - npm run build --verbose
  build:
    commands:
      - echo ID_qV2pTT9w
      - echo Creating tar.gz archive of build files...
      - cd build
      - tar -czvf ../PLN5000256.tar.gz *
  post_build:
    commands:
      - echo Pushing artifacts...
artifacts:
  files:
    - PLN5000256.tar.gz
